### ISSUE TITLE
Error executing search after updating from: v2.12.0 to v3.0.0

### ISSUE THREAD

**Issue by methnen** [andrealandonio/cloud-search#13]
This is the error in full that I get when hitting Test Connection:

```
Error: Error executing "Search" on "2013-01-01/search"; AWS HTTP error: cURL error 6: Could not resolve host: 2013-01-01 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for 2013-01-01/search
```

Anyone else seeing this and have any insight into what might be happening?

I can start digging though the code and looking for the actual failure point but if someone already has some insight into where it's failing I'd love to save the time.

**Comment by andrealandonio** [comment]
What's the value in the "**Search endpoint**" field for your plugin configuration? Have you defined protocol value in there?
like: 
https://search-endpoint-test-4okLpncykm262d5mt2pombm5wq.eu-central-1.cloudsearch.amazonaws.com

**Comment by methnen** [comment]
@andrealandonio Sorry for the delay in responding. Been a bit swamped lately.

Yes the Search endpoint field has a value. Same value it had previously, nothing changed in the settings.

**Comment by methnen** [comment]
Well, I'm definitely feeling lost as heck. 

I decided to create new access keys for the user with access to the cloud search stuff in AWS.

After updating those values I now get a completely new error:

```
Error: Error executing "Search" on "https://search-research-gigaom-local-bsev427fwkdxevexo6uih4euxa.us-west-1.cloudsearch.amazonaws.com/2013-01-01/search"; 
AWS HTTP error: Client error: `POST https://search-research-gigaom-local-xxxxxxxxxxx-west-1.cloudsearch.amazonaws.com/2013-01-01/search` resulted in a `400 Bad Request` 
response: { "error" : { "rid" : "xxxxxxxxxxx", "message" : "[*Deprecated*: Use the outer message field] Invalid Int (truncated...) (client): Invalid Integer: - { "error" : { "rid" : "xxxxxxxxxxx", "message" : "[*Deprecated*: Use the outer message field] Invalid Integer: " }, "message" : "Invalid Integer: ", "__type" : "#SearchException" }
```
The way the client stuff in the AWS classes is built I'm honestly having a hard time finding where the actual curl request is happening in any case.

**Comment by andrealandonio** [comment]
I don't think is a matter of credentials... which version of PHP are you using?

**Comment by methnen** [comment]
This is a local dev server. I see the same issue on PHP versions 8.0.8 AND 7.4.21.

Let me see if I can replicate this exactly on our staging server. In which case you could lay eyes on it directly.

**Comment by methnen** [comment]
OK, so the staging server exhibits the same issue as my last post. It's running PHP 7.4.

I'd be happy to pass you whatever credentials you needed if you were willing/wanted to look into it on the staging server.

Do you still use your Slack workspace?

I'm still on there I think and could you pass you more details that way if that's easier.

**Comment by methnen** [comment]
Just to follow up publicly, this turned out to be some faulty logic in a query condition that was being added to the ACS queries via a filter. By chance the issue cropped up right around the same time I updated the plugin so I falsely thought it was related to the update when it wasn't.
