### ISSUE TITLE
PHP 8.0 isn't supported (mainly due to use of v2 AWS SDK)

### ISSUE THREAD

**Issue by oppiansteve** [andrealandonio/cloud-search#4]
PHP 7.4 will stop getting security fixes before the end of the year.

I might be pressed to get to it soon, but would you like me to create a pull request updating this repo to use the v3 SDK?

Perhaps also baking in the use of php scoper to auto-scope the vendor directory elements (I've done that for my own projects).
And doesn't preclude the checking in of the vendor directory in the repo, should that be wanted.

**Comment by andrealandonio** [comment]
Sure, fill free to create a PR... actually I'm quite busy.. as soon as possible I'll take a look to this but if you want to send me your pull request could be a quick way for achieve that ;-)

**Comment by oppiansteve** [comment]
sorry, I missed your response - hopefully we'll take another look at this issue soon

**Comment by oppiansteve** [comment]
OK, so, I'm finally going to take a look at this, but it seems it is going to be tricky because of the manual steps needed to update SDKs etc.

So, my plan is to add in a build directory which will pull in necessary composer packages including a more modern AWS SDK. (this means we need to move support up to PHP 5.5 - the minimum needed for the SDK).

Then it will use phpscoper to automatically namespace the packages in the AWS SDK, Guzzle etc.

Then it will use a 'top-level' trivial `composer.json` to  create the classmaps etc. for the autoload.

I'm also tempted to make things easier for the old versions of grunt etc. by putting the whole build environment inside a docker instance/instances (that just overwrites the checked in build output for the markdown).

So, we will have a build directory that isn't needed at runtime and the 'built' files are checked in (as now), so people can just just unzip the plugin source to WP plugins to use.

Oh, also, my current plan is to just keep all the AWS SDK (which is the safest way to do it, I think), which will mean the plugin will get a lot bigger with (currently) unused parts of the AWS SDK.

I'm currently using Composer 2, which bumps up the required PHP to 5.6 at runtime.
If you want, I could change over to composer 1, which would support 5.5 too, but since even PHP 7.3 was end-of-lifed last year, perhaps we can take this as an opportunity to require a more recent PHP.
(I'm interested in trying pint and wp-stan on the code base to see what problems it shows up, but that's way out of scope with this pull request, of course)

Anyway, let me know if this sounds acceptable or there are red-flags for you.

**Comment by andrealandonio** [comment]
totally agree with Composer2 and it's a good moment for forcing a recent PHP requirements.. 

Maybe we can also release a major version of the plugin telling that PHP 8 is required.. just for users that want to upgrade to that, and keep the current release for the old PHP version.. what do you think about it?

**Comment by methnen** [comment]
Just came to report the same issue. Glad to see it's already being addressed. 

If the next version requires PHP8+ preserving the older version in some form would probably be a good idea. 

For people on hosting environments that are a bit more conservative about PHP versions.

**Comment by andrealandonio** [comment]
Solved releasing a new plugin version
